# Generated by Django 3.2.8 on 2021-10-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20211018_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sha',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
