# Generated by Django 3.2.8 on 2021-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='firstname',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='lastname',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
