# Generated by Django 3.2.8 on 2021-10-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20211023_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers'),
        ),
    ]
